MODEL:
  ARCH: "slowfast"                       # Model architecture
  NUM_CLASSES: 10                        # Number of classes in the dataset
  SLOWFAST:
    ALPHA: 8                             # Alpha for SlowFast
    BETA_INV: 8                          # Beta inverse for SlowFast
    FAST_FRAME_RATE: 1                    # Frames per second for the Fast pathway (1fps)
    SLOW_FRAME_RATE: 1                    # Frames per second for the Slow pathway (1fps)
DATA:
  TEST_DIR: "datasets/frames/test_videos"
  ANNOTATIONS: "datasets/annotations/json_test"
  BATCH_SIZE: 1                          # Batch size for inference
  NUM_WORKERS: 2                         # Data loader workers
  INPUT:
    MEAN: [0.45, 0.45, 0.45]             # Normalization mean
    STD: [0.225, 0.225, 0.225]           # Normalization standard deviation

CHECKPOINT:
  LOAD_PATH: "experiments/checkpoints/slowfast_epoch_50.pth"  # Load the checkpoint for inference

OUTPUT:
  SAVE_DIR: "experiments/predictions"   # Directory to save inference outputs
